// Auto-generated from Strategies 2026Q2.xlsx — DO NOT EDIT MANUALLY

export const PORTFOLIO_DATA = {
  corePrivate: [
    { name: "Vanguard S&P 500 ETF",       fullName: "[Passive] Vanguard S&P 500 ETF (VOO)",                       assetClass: "US Large Cap Core",       group: "Equity",       subGroup: "Domestic Equity",  ticker: "VOO",   fee: 0.04, allocs: { conservative: 1.75, moderatelyConservative: 2.75, conservativePlus: 4.25, balanced: 5.5,  balancedPlus: 7.0,  growth: 9.0,  growthPlus: 10.25, aggressive: 12.0  } },
    { name: "Aristotle Value Equity",      fullName: "Aristotle - Value Equity ($250K min)",                       assetClass: "US Large Cap Value",      group: "Equity",       subGroup: "Domestic Equity",  ticker: "SMA",   fee: 0.4,  allocs: { conservative: 2.25, moderatelyConservative: 3.75, conservativePlus: 5.5,  balanced: 7.0,  balancedPlus: 8.0,  growth: 9.25, growthPlus: 10.5,  aggressive: 12.5  } },
    { name: "Polen Growth (POLIX)",        fullName: "Polen Growth Institutional (POLIX)",                         assetClass: "US Large Cap Growth",     group: "Equity",       subGroup: "Domestic Equity",  ticker: "POLIX", fee: 0.0,  allocs: { conservative: 2.5,  moderatelyConservative: 4.0,  conservativePlus: 6.0,  balanced: 7.5,  balancedPlus: 9.0,  growth: 10.5, growthPlus: 12.0,  aggressive: 14.0  } },
    { name: "Vanguard Mid-Cap ETF",        fullName: "[Passive] Vanguard Mid-Cap ETF (VO)",                        assetClass: "US Mid Cap",              group: "Equity",       subGroup: "Domestic Equity",  ticker: "VO",    fee: 0.05, allocs: { conservative: 0.0,  moderatelyConservative: 1.75, conservativePlus: 2.5,  balanced: 3.25, balancedPlus: 4.0,  growth: 4.75, growthPlus: 5.5,   aggressive: 6.25  } },
    { name: "River Road Small Cap",        fullName: "River Road Asset Mgmt (Small Cap) (ARSIX)",                  assetClass: "US Small Cap",            group: "Equity",       subGroup: "Domestic Equity",  ticker: "ARSIX", fee: 1.18, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.25,  aggressive: 2.75  } },
    { name: "Artisan Intl Value",          fullName: "Artisan International Value (ARTKX)",                        assetClass: "Intl Developed Value",    group: "Equity",       subGroup: "Intl Developed",   ticker: "ARTKX", fee: 0.63, allocs: { conservative: 2.0,  moderatelyConservative: 3.25, conservativePlus: 5.0,  balanced: 6.5,  balancedPlus: 8.0,  growth: 9.75, growthPlus: 11.25, aggressive: 13.0  } },
    { name: "EuroPacific Growth",          fullName: "EuroPacific Growth Fund (FEUPX)",                            assetClass: "Intl Developed Growth",   group: "Equity",       subGroup: "Intl Developed",   ticker: "APHIX", fee: 0.96, allocs: { conservative: 2.5,  moderatelyConservative: 4.0,  conservativePlus: 6.0,  balanced: 7.75, balancedPlus: 9.5,  growth: 11.25,growthPlus: 13.0,  aggressive: 15.0  } },
    { name: "Oppenheimer Dev. Mkts",       fullName: "OppenheimerFunds (Developing Mkts Eq) (ODVIX)",              assetClass: "Emerging Markets",        group: "Equity",       subGroup: "Emerging Markets", ticker: "ODVIX", fee: 0.88, allocs: { conservative: 0.0,  moderatelyConservative: 2.0,  conservativePlus: 3.25, balanced: 4.0,  balancedPlus: 5.0,  growth: 6.0,  growthPlus: 7.0,   aggressive: 8.0   } },
    { name: "Belle Haven Muni Plus",       fullName: "Belle Haven Muni Plus",                                      assetClass: "Core/Muni Bonds",         group: "Fixed Income", subGroup: "Fixed Income",     ticker: "MUB",   fee: 0.41, allocs: { conservative: 65.5, moderatelyConservative: 55.5, conservativePlus: 44.5, balanced: 33.0, balancedPlus: 21.5, growth: 12.5, growthPlus: 1.75,  aggressive: 0.0   } },
    { name: "iShares Short Muni ETF",      fullName: "[Passive] i Shares Short-tem Muni bond ETF(SUB)",            assetClass: "Short-Term Fixed",        group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SUB",   fee: 0.75, allocs: { conservative: 5.0,  moderatelyConservative: 4.5,  conservativePlus: 4.5,  balanced: 4.0,  balancedPlus: 3.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Schwab TIPS ETF",             fullName: "[Passive] Schwab US TIPS ETF™ (SCHP)",                       assetClass: "US TIPS",                 group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SCHP",  fee: 0.05, allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Partners Group",              fullName: "Partners Group LLC",                                         assetClass: "Private Equity",          group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 2.31, allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 3.0,  growth: 3.0,  growthPlus: 4.5,   aggressive: 4.5   } },
    { name: "Griffin RE (GRIFX)",          fullName: "Griffin Institutional Access Real Estate Fund (GRIFX)",      assetClass: "Real Estate",             group: "Alternatives", subGroup: "Alternatives",     ticker: "GRIFX", fee: 1.72, allocs: { conservative: 4.0,  moderatelyConservative: 4.0,  conservativePlus: 3.0,  balanced: 3.0,  balancedPlus: 2.75, growth: 2.5,  growthPlus: 2.25,  aggressive: 2.5   } },
    { name: "North Rock",                  fullName: "North Rock",                                                 assetClass: "Hedge Funds",             group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 1.5,  allocs: { conservative: 2.5,  moderatelyConservative: 2.5,  conservativePlus: 2.5,  balanced: 2.5,  balancedPlus: 3.0,  growth: 3.0,  growthPlus: 3.0,   aggressive: 0.0   } },
    { name: "JPM Hedged Equity II",        fullName: "JP Morgan Hedged Equity II (JHQDX)",                         assetClass: "Hedged Equity",           group: "Alternatives", subGroup: "Alternatives",     ticker: "JHQDX", fee: 0.6,  allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 3.0,  growth: 3.0,  growthPlus: 3.0,   aggressive: 0.0   } },
    { name: "Cohen & Steers Real Assets",  fullName: "Cohen & Steers Real Asset Fund (RAPIX)",                     assetClass: "Real Assets & Other Alts",group: "Alternatives", subGroup: "Alternatives",     ticker: "RAPIX", fee: 0.81, allocs: { conservative: 3.0,  moderatelyConservative: 3.0,  conservativePlus: 3.0,  balanced: 3.0,  balancedPlus: 3.0,  growth: 3.0,  growthPlus: 3.0,   aggressive: 3.0   } },
    { name: "Cliffwater Direct Lending",   fullName: "Cliffwater Direct Lending Fund (CCLFX)",                     assetClass: "Private Credit",          group: "Alternatives", subGroup: "Alternatives",     ticker: "CCLFX", fee: 2.32, allocs: { conservative: 3.0,  moderatelyConservative: 3.0,  conservativePlus: 2.0,  balanced: 3.0,  balancedPlus: 3.75, growth: 3.5,  growthPlus: 3.25,  aggressive: 3.5   } },
    { name: "Beacon Pointe Multi-Alt",     fullName: "Beacon Pointe Multi-Alternative Fund (BPMAX)",                assetClass: "Diversified Alternatives",group: "Alternatives", subGroup: "Alternatives",     ticker: "BPMAX", fee: 3.29, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.5,  growth: 3.0,  growthPlus: 3.5,   aggressive: 3.0   } },
    { name: "Cash",                        fullName: "Cash / Cash Equivalents",                                    assetClass: "Cash",                    group: "Cash",         subGroup: "Cash",             ticker: "SHV",   fee: 0.15, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
  ],
  selectLiquidity: [
    { name: "Vanguard S&P 500 ETF",       fullName: "[Passive] Vanguard S&P 500 ETF (VOO)",                       assetClass: "US Large Cap Core",       group: "Equity",       subGroup: "Domestic Equity",  ticker: "VOO",   fee: 0.04, allocs: { conservative: 1.75, moderatelyConservative: 2.75, conservativePlus: 4.25, balanced: 5.5,  balancedPlus: 7.0,  growth: 9.0,  growthPlus: 10.25, aggressive: 12.0  } },
    { name: "Aristotle Value Equity",      fullName: "Aristotle - Value Equity ($250K min)",                       assetClass: "US Large Cap Value",      group: "Equity",       subGroup: "Domestic Equity",  ticker: "SMA",   fee: 0.4,  allocs: { conservative: 2.25, moderatelyConservative: 3.75, conservativePlus: 5.5,  balanced: 7.0,  balancedPlus: 8.0,  growth: 9.25, growthPlus: 10.5,  aggressive: 12.5  } },
    { name: "Polen Growth (POLIX)",        fullName: "Polen Growth Institutional (POLIX)",                         assetClass: "US Large Cap Growth",     group: "Equity",       subGroup: "Domestic Equity",  ticker: "POLIX", fee: 0.0,  allocs: { conservative: 2.5,  moderatelyConservative: 4.0,  conservativePlus: 6.0,  balanced: 7.5,  balancedPlus: 9.0,  growth: 10.5, growthPlus: 12.0,  aggressive: 14.0  } },
    { name: "Vanguard Mid-Cap ETF",        fullName: "[Passive] Vanguard Mid-Cap ETF (VO)",                        assetClass: "US Mid Cap",              group: "Equity",       subGroup: "Domestic Equity",  ticker: "VO",    fee: 0.05, allocs: { conservative: 0.0,  moderatelyConservative: 1.75, conservativePlus: 2.5,  balanced: 3.25, balancedPlus: 4.0,  growth: 4.75, growthPlus: 5.5,   aggressive: 6.25  } },
    { name: "River Road Small Cap",        fullName: "River Road Asset Mgmt (Small Cap) (ARSIX)",                  assetClass: "US Small Cap",            group: "Equity",       subGroup: "Domestic Equity",  ticker: "ARSIX", fee: 1.18, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.25,  aggressive: 2.75  } },
    { name: "Dodge & Cox Intl",            fullName: "Dodge & Cox (International Stock Fund) (DODFX)",             assetClass: "Intl Developed Value",    group: "Equity",       subGroup: "Intl Developed",   ticker: "DODFX", fee: 0.63, allocs: { conservative: 2.0,  moderatelyConservative: 3.25, conservativePlus: 5.0,  balanced: 6.5,  balancedPlus: 8.0,  growth: 9.75, growthPlus: 11.25, aggressive: 13.0  } },
    { name: "Artisan International",       fullName: "Artisan International (APHIX)",                              assetClass: "Intl Developed Growth",   group: "Equity",       subGroup: "Intl Developed",   ticker: "APHIX", fee: 0.96, allocs: { conservative: 2.5,  moderatelyConservative: 4.0,  conservativePlus: 6.0,  balanced: 7.75, balancedPlus: 9.5,  growth: 11.25,growthPlus: 13.0,  aggressive: 15.0  } },
    { name: "Oppenheimer Dev. Mkts",       fullName: "OppenheimerFunds (Developing Mkts Eq) (ODVIX)",              assetClass: "Emerging Markets",        group: "Equity",       subGroup: "Emerging Markets", ticker: "ODVIX", fee: 0.88, allocs: { conservative: 0.0,  moderatelyConservative: 2.0,  conservativePlus: 3.25, balanced: 4.0,  balancedPlus: 5.0,  growth: 6.0,  growthPlus: 7.0,   aggressive: 8.0   } },
    { name: "Belle Haven Muni Plus",       fullName: "Belle Haven Muni Plus",                                      assetClass: "Core/Muni Bonds",         group: "Fixed Income", subGroup: "Fixed Income",     ticker: "MUB",   fee: 0.41, allocs: { conservative: 65.5, moderatelyConservative: 55.5, conservativePlus: 44.5, balanced: 33.0, balancedPlus: 21.5, growth: 12.5, growthPlus: 1.75,  aggressive: 0.0   } },
    { name: "iShares Short Muni ETF",      fullName: "[Passive] i Shares Short-tem Muni bond ETF(SUB)",            assetClass: "Short-Term Fixed",        group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SUB",   fee: 0.75, allocs: { conservative: 5.0,  moderatelyConservative: 4.5,  conservativePlus: 4.5,  balanced: 4.0,  balancedPlus: 3.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Schwab TIPS ETF",             fullName: "[Passive] Schwab US TIPS ETF™ (SCHP)",                       assetClass: "US TIPS",                 group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SCHP",  fee: 0.05, allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    // ── Alternatives ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    // Private Equity and Hedge Funds now carry real allocations; Griffin RE and Cliffwater
    // are reduced proportionally to keep every risk-profile column summing to 100%.
    { name: "Partners Group",              fullName: "Partners Group LLC",                                         assetClass: "Private Equity",          group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 2.31, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 2.0,  balancedPlus: 2.5,  growth: 3.0,  growthPlus: 4.0,   aggressive: 4.0   } },
    { name: "Griffin RE (GRIFX)",          fullName: "Griffin Institutional Access Real Estate Fund (GRIFX)",      assetClass: "Real Estate",             group: "Alternatives", subGroup: "Alternatives",     ticker: "GRIFX", fee: 1.72, allocs: { conservative: 6.0,  moderatelyConservative: 6.0,  conservativePlus: 5.0,  balanced: 3.0,  balancedPlus: 3.0,  growth: 2.5,  growthPlus: 2.75,  aggressive: 3.0   } },
    { name: "North Rock",                  fullName: "North Rock",                                                 assetClass: "Hedge Funds",             group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 1.5,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.5,  growth: 3.0,  growthPlus: 3.0,   aggressive: 0.0   } },
    { name: "JPM Hedged Equity II",        fullName: "JP Morgan Hedged Equity II (JHQDX)",                         assetClass: "Hedged Equity",           group: "Alternatives", subGroup: "Alternatives",     ticker: "JHQDX", fee: 0.6,  allocs: { conservative: 3.25, moderatelyConservative: 3.25, conservativePlus: 3.25, balanced: 3.25, balancedPlus: 4.5,  growth: 4.5,  growthPlus: 4.5,   aggressive: 0.0   } },
    { name: "Cohen & Steers Real Assets",  fullName: "Cohen & Steers Real Asset Fund (RAPIX)",                     assetClass: "Real Assets & Other Alts",group: "Alternatives", subGroup: "Alternatives",     ticker: "RAPIX", fee: 0.81, allocs: { conservative: 3.0,  moderatelyConservative: 3.0,  conservativePlus: 3.0,  balanced: 3.0,  balancedPlus: 3.0,  growth: 3.0,  growthPlus: 3.0,   aggressive: 3.0   } },
    { name: "Cliffwater Direct Lending",   fullName: "Cliffwater Direct Lending Fund (CCLFX)",                     assetClass: "Private Credit",          group: "Alternatives", subGroup: "Alternatives",     ticker: "CCLFX", fee: 2.32, allocs: { conservative: 4.25, moderatelyConservative: 4.25, conservativePlus: 3.25, balanced: 2.25, balancedPlus: 3.0,  growth: 2.0,  growthPlus: 1.75,  aggressive: 3.5   } },
    { name: "Beacon Pointe Multi-Alt",     fullName: "Beacon Pointe Multi-Alternative Fund (BPMAX)",                assetClass: "Diversified Alternatives",group: "Alternatives", subGroup: "Alternatives",     ticker: "BPMAX", fee: 3.29, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.5,  growth: 3.0,  growthPlus: 3.5,   aggressive: 3.0   } },
    { name: "Cash",                        fullName: "Cash / Cash Equivalents",                                    assetClass: "Cash",                    group: "Cash",         subGroup: "Cash",             ticker: "SHV",   fee: 0.15, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
  ],
  traditional: [
    { name: "Vanguard S&P 500 ETF",       fullName: "[Passive] Vanguard S&P 500 ETF (VOO)",                       assetClass: "US Large Cap Core",       group: "Equity",       subGroup: "Domestic Equity",  ticker: "VOO",   fee: 0.04, allocs: { conservative: 2.5,  moderatelyConservative: 3.75, conservativePlus: 4.75, balanced: 6.25, balancedPlus: 8.0,  growth: 10.0, growthPlus: 11.5,  aggressive: 14.0  } },
    { name: "Aristotle Value Equity",      fullName: "Aristotle - Value Equity ($250K min)",                       assetClass: "US Large Cap Value",      group: "Equity",       subGroup: "Domestic Equity",  ticker: "SMA",   fee: 0.4,  allocs: { conservative: 3.0,  moderatelyConservative: 4.5,  conservativePlus: 6.25, balanced: 8.0,  balancedPlus: 9.0,  growth: 10.25,growthPlus: 12.0,  aggressive: 14.25 } },
    { name: "Polen Growth (POLIX)",        fullName: "Polen Growth Institutional (POLIX)",                         assetClass: "US Large Cap Growth",     group: "Equity",       subGroup: "Domestic Equity",  ticker: "POLIX", fee: 0.0,  allocs: { conservative: 3.25, moderatelyConservative: 5.0,  conservativePlus: 6.75, balanced: 8.5,  balancedPlus: 10.25,growth: 11.75,growthPlus: 13.5,  aggressive: 16.25 } },
    { name: "Vanguard Mid-Cap ETF",        fullName: "[Passive] Vanguard Mid-Cap ETF (VO)",                        assetClass: "US Mid Cap",              group: "Equity",       subGroup: "Domestic Equity",  ticker: "VO",    fee: 0.05, allocs: { conservative: 0.0,  moderatelyConservative: 2.25, conservativePlus: 3.0,  balanced: 3.75, balancedPlus: 4.5,  growth: 5.25, growthPlus: 6.0,   aggressive: 7.5   } },
    { name: "River Road Small Cap",        fullName: "River Road Asset Mgmt (Small Cap) (ARSIX)",                  assetClass: "US Small Cap",            group: "Equity",       subGroup: "Domestic Equity",  ticker: "ARSIX", fee: 1.18, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 1.75, balanced: 2.25, balancedPlus: 2.25, growth: 2.25, growthPlus: 2.5,   aggressive: 3.0   } },
    { name: "Dodge & Cox Intl",            fullName: "Dodge & Cox (International Stock Fund) (DODFX)",             assetClass: "Intl Developed Value",    group: "Equity",       subGroup: "Intl Developed",   ticker: "DODFX", fee: 0.63, allocs: { conservative: 3.0,  moderatelyConservative: 4.25, conservativePlus: 5.75, balanced: 7.5,  balancedPlus: 9.0,  growth: 10.75,growthPlus: 12.5,  aggressive: 15.25 } },
    { name: "Artisan International",       fullName: "Artisan International (APHIX)",                              assetClass: "Intl Developed Growth",   group: "Equity",       subGroup: "Intl Developed",   ticker: "APHIX", fee: 0.96, allocs: { conservative: 3.5,  moderatelyConservative: 5.0,  conservativePlus: 6.75, balanced: 8.75, balancedPlus: 10.75,growth: 12.5, growthPlus: 14.5,  aggressive: 17.5  } },
    { name: "Oppenheimer Dev. Mkts",       fullName: "OppenheimerFunds (Developing Mkts Eq) (ODVIX)",              assetClass: "Emerging Markets",        group: "Equity",       subGroup: "Emerging Markets", ticker: "ODVIX", fee: 0.88, allocs: { conservative: 1.75, moderatelyConservative: 2.75, conservativePlus: 3.5,  balanced: 4.5,  balancedPlus: 5.75, growth: 6.75, growthPlus: 7.75,  aggressive: 9.25  } },
    { name: "Belle Haven Muni Plus",       fullName: "Belle Haven Muni Plus",                                      assetClass: "Core/Muni Bonds",         group: "Fixed Income", subGroup: "Fixed Income",     ticker: "MUB",   fee: 0.41, allocs: { conservative: 73.0, moderatelyConservative: 63.0, conservativePlus: 52.0, balanced: 41.5, balancedPlus: 32.5, growth: 23.5, growthPlus: 12.75, aggressive: 0.0   } },
    { name: "iShares Short Muni ETF",      fullName: "[Passive] i Shares Short-tem Muni bond ETF(SUB)",            assetClass: "Short-Term Fixed",        group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SUB",   fee: 0.75, allocs: { conservative: 5.0,  moderatelyConservative: 4.5,  conservativePlus: 4.5,  balanced: 4.0,  balancedPlus: 3.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Schwab TIPS ETF",             fullName: "[Passive] Schwab US TIPS ETF™ (SCHP)",                       assetClass: "US TIPS",                 group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SCHP",  fee: 0.05, allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Partners Group",              fullName: "Partners Group LLC",                                         assetClass: "Private Equity",          group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 2.31, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Griffin RE (GRIFX)",          fullName: "Griffin Institutional Access Real Estate Fund (GRIFX)",      assetClass: "Real Estate",             group: "Alternatives", subGroup: "Alternatives",     ticker: "GRIFX", fee: 1.72, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "North Rock",                  fullName: "North Rock",                                                 assetClass: "Hedge Funds",             group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 1.5,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "JPM Hedged Equity II",        fullName: "JP Morgan Hedged Equity II (JHQDX)",                         assetClass: "Hedged Equity",           group: "Alternatives", subGroup: "Alternatives",     ticker: "JHQDX", fee: 0.6,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cohen & Steers Real Assets",  fullName: "Cohen & Steers Real Asset Fund (RAPIX)",                     assetClass: "Real Assets & Other Alts",group: "Alternatives", subGroup: "Alternatives",     ticker: "RAPIX", fee: 0.81, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cliffwater Direct Lending",   fullName: "Cliffwater Direct Lending Fund (CCLFX)",                     assetClass: "Private Credit",          group: "Alternatives", subGroup: "Alternatives",     ticker: "CCLFX", fee: 2.32, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Diversified Alternatives",    fullName: "Diversified Alternatives (Advisor Select)",                   assetClass: "Diversified Alternatives",group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 0.0,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cash",                        fullName: "Cash / Cash Equivalents",                                    assetClass: "Cash",                    group: "Cash",         subGroup: "Cash",             ticker: "SHV",   fee: 0.15, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
  ],
  focusedB: [
    { name: "Vanguard S&P 500 ETF",       fullName: "[Passive] Vanguard S&P 500 ETF (VOO)",                       assetClass: "US Large Cap Core",       group: "Equity",       subGroup: "Domestic Equity",  ticker: "VOO",   fee: 0.04, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Aristotle Value Equity",      fullName: "Aristotle - Value Equity ($250K min)",                       assetClass: "US Large Cap Value",      group: "Equity",       subGroup: "Domestic Equity",  ticker: "SMA",   fee: 0.4,  allocs: { conservative: 4.25, moderatelyConservative: 6.5,  conservativePlus: 9.0,  balanced: 11.25,balancedPlus: 13.5, growth: 15.5, growthPlus: 18.0,  aggressive: 21.5  } },
    { name: "Polen Growth (POLIX)",        fullName: "Polen Growth Institutional (POLIX)",                         assetClass: "US Large Cap Growth",     group: "Equity",       subGroup: "Domestic Equity",  ticker: "POLIX", fee: 0.0,  allocs: { conservative: 5.0,  moderatelyConservative: 7.5,  conservativePlus: 10.0, balanced: 13.0, balancedPlus: 15.25,growth: 17.75,growthPlus: 20.25, aggressive: 24.5  } },
    { name: "Vanguard Mid-Cap ETF",        fullName: "[Passive] Vanguard Mid-Cap ETF (VO)",                        assetClass: "US Mid Cap",              group: "Equity",       subGroup: "Domestic Equity",  ticker: "VO",    fee: 0.05, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "River Road Small Cap",        fullName: "River Road Asset Mgmt (Small Cap) (ARSIX)",                  assetClass: "US Small Cap",            group: "Equity",       subGroup: "Domestic Equity",  ticker: "ARSIX", fee: 1.18, allocs: { conservative: 2.25, moderatelyConservative: 3.25, conservativePlus: 4.5,  balanced: 5.75, balancedPlus: 6.75, growth: 7.75, growthPlus: 9.0,   aggressive: 10.75 } },
    { name: "Dodge & Cox Intl",            fullName: "Dodge & Cox (International Stock Fund) (DODFX)",             assetClass: "Intl Developed Value",    group: "Equity",       subGroup: "Intl Developed",   ticker: "DODFX", fee: 0.63, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Artisan International",       fullName: "Artisan International (APHIX)",                              assetClass: "Intl Developed Growth",   group: "Equity",       subGroup: "Intl Developed",   ticker: "APHIX", fee: 0.96, allocs: { conservative: 6.5,  moderatelyConservative: 10.25,conservativePlus: 14.0, balanced: 17.5, balancedPlus: 21.0, growth: 24.5, growthPlus: 28.0,  aggressive: 34.25 } },
    { name: "Oppenheimer Dev. Mkts",       fullName: "OppenheimerFunds (Developing Mkts Eq) (ODVIX)",              assetClass: "Emerging Markets",        group: "Equity",       subGroup: "Emerging Markets", ticker: "ODVIX", fee: 0.88, allocs: { conservative: 2.0,  moderatelyConservative: 3.0,  conservativePlus: 4.0,  balanced: 5.0,  balancedPlus: 6.0,  growth: 7.0,  growthPlus: 8.0,   aggressive: 9.0   } },
    { name: "Belle Haven Muni Plus",       fullName: "Belle Haven Muni Plus",                                      assetClass: "Core/Muni Bonds",         group: "Fixed Income", subGroup: "Fixed Income",     ticker: "MUB",   fee: 0.41, allocs: { conservative: 78.0, moderatelyConservative: 67.5, conservativePlus: 56.5, balanced: 45.5, balancedPlus: 35.5, growth: 25.5, growthPlus: 14.75, aggressive: 0.0   } },
    { name: "iShares Short Muni ETF",      fullName: "[Passive] i Shares Short-tem Muni bond ETF(SUB)",            assetClass: "Short-Term Fixed",        group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SUB",   fee: 0.75, allocs: { conservative: 2.0,  moderatelyConservative: 2.0,  conservativePlus: 2.0,  balanced: 2.0,  balancedPlus: 2.0,  growth: 2.0,  growthPlus: 2.0,   aggressive: 0.0   } },
    { name: "Schwab TIPS ETF",             fullName: "[Passive] Schwab US TIPS ETF™ (SCHP)",                       assetClass: "US TIPS",                 group: "Fixed Income", subGroup: "Fixed Income",     ticker: "SCHP",  fee: 0.05, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Partners Group",              fullName: "Partners Group LLC",                                         assetClass: "Private Equity",          group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 2.31, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Griffin RE (GRIFX)",          fullName: "Griffin Institutional Access Real Estate Fund (GRIFX)",      assetClass: "Real Estate",             group: "Alternatives", subGroup: "Alternatives",     ticker: "GRIFX", fee: 1.72, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "North Rock",                  fullName: "North Rock",                                                 assetClass: "Hedge Funds",             group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 1.5,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "JPM Hedged Equity II",        fullName: "JP Morgan Hedged Equity II (JHQDX)",                         assetClass: "Hedged Equity",           group: "Alternatives", subGroup: "Alternatives",     ticker: "JHQDX", fee: 0.6,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cohen & Steers Real Assets",  fullName: "Cohen & Steers Real Asset Fund (RAPIX)",                     assetClass: "Real Assets & Other Alts",group: "Alternatives", subGroup: "Alternatives",     ticker: "RAPIX", fee: 0.81, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cliffwater Direct Lending",   fullName: "Cliffwater Direct Lending Fund (CCLFX)",                     assetClass: "Private Credit",          group: "Alternatives", subGroup: "Alternatives",     ticker: "CCLFX", fee: 2.32, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Diversified Alternatives",    fullName: "Diversified Alternatives (Advisor Select)",                   assetClass: "Diversified Alternatives",group: "Alternatives", subGroup: "Alternatives",     ticker: "N/A",   fee: 0.0,  allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
    { name: "Cash",                        fullName: "Cash / Cash Equivalents",                                    assetClass: "Cash",                    group: "Cash",         subGroup: "Cash",             ticker: "SHV",   fee: 0.15, allocs: { conservative: 0.0,  moderatelyConservative: 0.0,  conservativePlus: 0.0,  balanced: 0.0,  balancedPlus: 0.0,  growth: 0.0,  growthPlus: 0.0,   aggressive: 0.0   } },
  ],
};

// Maps portfolio key aliases to data keys
export const MODEL_ALIAS = {
  corePrivate:           "corePrivate",
  selectLiquidity:       "selectLiquidity",
  selectLiquidityUsBias: "selectLiquidity",
  traditional:           "traditional",
  traditionalUsBias:     "traditional",
  focusedB:              "focusedB",
};

// Models that include an alternatives sleeve (CorePrivate & SelectLiquidity only)
const MODELS_WITH_ALTERNATIVES = new Set(["corePrivate", "selectLiquidity"]);

/** Returns funds with alloc > 0 for the given model + risk profile (used by ppt slides).
 *  Defensively zeroes any Alternatives-group allocation for models that don't carry an
 *  alternatives sleeve (Traditional, FocusedB), even if the underlying data is non-zero. */
export function getFunds(modelKey, riskProfileKey) {
  const key   = MODEL_ALIAS[modelKey] || modelKey || "corePrivate";
  const funds = PORTFOLIO_DATA[key] || PORTFOLIO_DATA.corePrivate;
  return funds
    .map(f => ({ ...f, alloc: (!MODELS_WITH_ALTERNATIVES.has(key) && f.group === "Alternatives") ? 0 : (f.allocs[riskProfileKey] || 0) }))
    .filter(f => f.alloc > 0);
}

/** Returns ALL funds for the model (including 0% ones) with alloc attached.
 *  Used by the preview modal so the full fund lineup is always visible.
 *  Same defensive Alternatives suppression as getFunds. */
export function getAllFunds(modelKey, riskProfileKey) {
  const key   = MODEL_ALIAS[modelKey] || modelKey || "corePrivate";
  const funds = PORTFOLIO_DATA[key] || PORTFOLIO_DATA.corePrivate;
  return funds.map(f => ({ ...f, alloc: (!MODELS_WITH_ALTERNATIVES.has(key) && f.group === "Alternatives") ? 0 : (f.allocs[riskProfileKey] || 0) }));
}

/** Sums alloc% by broad group: Equity / Fixed Income / Alternatives / Cash */
export function getGroupTotals(modelKey, riskProfileKey) {
  const funds = getFunds(modelKey, riskProfileKey);
  const t = { Equity: 0, "Fixed Income": 0, Alternatives: 0, Cash: 0 };
  for (const f of funds) t[f.group] = (t[f.group] || 0) + f.alloc;
  return t;
}

/** Sums alloc% by 6 donut segments: Domestic Equity, Intl Developed, Emerging Markets,
 *  Fixed Income, Alternatives, Cash — zeros omitted automatically by donut renderer.
 *  Alternatives are suppressed to 0 for models that don't use them (Traditional, FocusedB). */
export function getSubGroupTotals(modelKey, riskProfileKey) {
  const resolvedKey = MODEL_ALIAS[modelKey] || modelKey || "corePrivate";
  const funds = getFunds(modelKey, riskProfileKey);
  const t = {
    "Domestic Equity":  0,
    "Intl Developed":   0,
    "Emerging Markets": 0,
    "Fixed Income":     0,
    "Alternatives":     0,
    "Cash":             0,
  };
  for (const f of funds) {
    // Suppress Alternatives for models that don't use them (Traditional, FocusedB)
    if (!MODELS_WITH_ALTERNATIVES.has(resolvedKey) && f.subGroup === "Alternatives") continue;
    t[f.subGroup] = (t[f.subGroup] || 0) + f.alloc;
  }
  return t;
}
